name: domain-ner
channels:
  - pytorch
  - defaults
dependencies:
  - black
  - cudatoolkit=10.2
  - dill
  - matplotlib
  - nltk
  - numpy
  - pandas
  - pillow
  - pip
  - python
  - pytorch
  - scikit-learn
  - torchvision
  - pip:
    - pytorch-crf
    - pytorch-nlp
    - pyyaml
    - mlflow
    - pytesseract
    - opencv-python
