name: domain-ner
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=10.2
  - nltk
  - pip:
      - scikit-learn
      - mlflow
      - pytorch-crf
      - pytorch-nlp
      - dill
      - matplotlib
      - nltk